<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AdminNewsSaveRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
//    public function authorize()
//    {
//        return false;
//    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required|min:10|max:50|unique:news',
            'summary' => 'max:100|required',
            'category_id' => 'required|integer|exists:categories,id',
            'source_id' => 'required|integer|exists:sources,id',
            'status_id' => 'required|integer|exists:statuses,id',
            'image' => 'max:100',
            'content' => 'required',
            'publish_date' => 'date'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return [
            'title' =>(__('labels.title')),
            'summary' =>(__('labels.summary')),
            'content' =>(__('labels.content')),
            'publish_date' =>(__('labels.publish_date')),
        ];
    }
}
